spring:
  application:
    name: vmall-eureka
  security:
    user:
      name: javaboy
      password: 123
server:
  port: 8848
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://javaboy:123@localhost:8848/eureka/