spring:
  application:
    name: vmall-gateway
server:
  port: 8000
zuul:
  routes:
    vmall-seller-auth: /auth/**
    vmall-merchandise: /merchandise/**
    vmall-app-manager: /appmanager/**
    vmall-file-server: /file/**
  sensitive-headers:
eureka:
  client:
    service-url:
      defaultZone: http://javaboy:123@localhost:8848/eureka