spring:
  application:
    name: vmall-seller-auth
  datasource:
    url: jdbc:mysql:///vmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  main:
    allow-bean-definition-overriding: true
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://javaboy:123@localhost:8848/eureka